# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TDDRecipe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TDDRecipe

  target 'TDDRecipeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapKit', '~> 3.0'
  end

end
