# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TDDRecipe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 3.2.0'
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'

  target 'TDDRecipeTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest', '~> 3.0'
  end
end
